# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HealthcareWorkerAuthPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HealthCareWorkerAuthPage(object):
    def setupUi(self, HealthCareWorkerAuthPage):
        HealthCareWorkerAuthPage.setObjectName("HealthCareWorkerAuthPage")
        HealthCareWorkerAuthPage.resize(400, 300)
        HealthCareWorkerAuthPage.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.lbl_auth = QtWidgets.QLabel(HealthCareWorkerAuthPage)
        self.lbl_auth.setGeometry(QtCore.QRect(90, 90, 201, 16))
        self.lbl_auth.setObjectName("lbl_auth")
        self.et_hcwPRN = QtWidgets.QLineEdit(HealthCareWorkerAuthPage)
        self.et_hcwPRN.setGeometry(QtCore.QRect(90, 120, 201, 22))
        self.et_hcwPRN.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.et_hcwPRN.setEchoMode(QtWidgets.QLineEdit.Password)
        self.et_hcwPRN.setObjectName("et_hcwPRN")
        self.btn_profRegSubmit = QtWidgets.QPushButton(HealthCareWorkerAuthPage)
        self.btn_profRegSubmit.setGeometry(QtCore.QRect(130, 160, 93, 28))
        self.btn_profRegSubmit.setObjectName("btn_profRegSubmit")
        self.btn_rtnHme = QtWidgets.QPushButton(HealthCareWorkerAuthPage)
        self.btn_rtnHme.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.btn_rtnHme.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Res/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rtnHme.setIcon(icon)
        self.btn_rtnHme.setIconSize(QtCore.QSize(30, 30))
        self.btn_rtnHme.setObjectName("btn_rtnHme")
        self.lb_hcwNotice = QtWidgets.QLabel(HealthCareWorkerAuthPage)
        self.lb_hcwNotice.setGeometry(QtCore.QRect(60, 220, 271, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_hcwNotice.setFont(font)
        self.lb_hcwNotice.setObjectName("lb_hcwNotice")

        self.retranslateUi(HealthCareWorkerAuthPage)
        QtCore.QMetaObject.connectSlotsByName(HealthCareWorkerAuthPage)

    def retranslateUi(self, HealthCareWorkerAuthPage):
        _translate = QtCore.QCoreApplication.translate
        HealthCareWorkerAuthPage.setWindowTitle(_translate("HealthCareWorkerAuthPage", "Electronic Vaccination Data System"))
        self.lbl_auth.setText(_translate("HealthCareWorkerAuthPage", "Professsional Registration Number"))
        self.btn_profRegSubmit.setText(_translate("HealthCareWorkerAuthPage", "S u b m i t"))
        self.btn_rtnHme.setToolTip(_translate("HealthCareWorkerAuthPage", "Home"))
        self.lb_hcwNotice.setText(_translate("HealthCareWorkerAuthPage", "Incorrect PRN Entered, please try again."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HealthCareWorkerAuthPage = QtWidgets.QWidget()
    ui = Ui_HealthCareWorkerAuthPage()
    ui.setupUi(HealthCareWorkerAuthPage)
    HealthCareWorkerAuthPage.show()
    sys.exit(app.exec_())
