# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LandingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LandingPage(object):
    def setupUi(self, LandingPage):
        LandingPage.setObjectName("LandingPage")
        LandingPage.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LandingPage)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_hcw = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hcw.setGeometry(QtCore.QRect(310, 160, 131, 28))
        self.btn_hcw.setObjectName("btn_hcw")
        self.btn_ptntReg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ptntReg.setGeometry(QtCore.QRect(310, 210, 131, 28))
        self.btn_ptntReg.setObjectName("btn_ptntReg")
        self.btn_ptntUpdt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ptntUpdt.setGeometry(QtCore.QRect(310, 260, 131, 28))
        self.btn_ptntUpdt.setObjectName("btn_ptntUpdt")
        LandingPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LandingPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        LandingPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LandingPage)
        self.statusbar.setObjectName("statusbar")
        LandingPage.setStatusBar(self.statusbar)

        self.retranslateUi(LandingPage)
        QtCore.QMetaObject.connectSlotsByName(LandingPage)

    def retranslateUi(self, LandingPage):
        _translate = QtCore.QCoreApplication.translate
        LandingPage.setWindowTitle(_translate("LandingPage", "Electronic Vaccination Data System"))
        self.btn_hcw.setText(_translate("LandingPage", "Health-Care Worker"))
        self.btn_ptntReg.setText(_translate("LandingPage", "Patient Registration"))
        self.btn_ptntUpdt.setText(_translate("LandingPage", "Update Appointment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LandingPage = QtWidgets.QMainWindow()
    ui = Ui_LandingPage()
    ui.setupUi(LandingPage)
    LandingPage.show()
    sys.exit(app.exec_())
