# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientAppointmentUpdatePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatientAppointmentUpdatePage(object):
    def setupUi(self, PatientAppointmentUpdatePage):
        PatientAppointmentUpdatePage.setObjectName("PatientAppointmentUpdatePage")
        PatientAppointmentUpdatePage.resize(400, 300)
        self.label = QtWidgets.QLabel(PatientAppointmentUpdatePage)
        self.label.setGeometry(QtCore.QRect(40, 40, 55, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(PatientAppointmentUpdatePage)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 151, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.btn_ptntUpdateVerify = QtWidgets.QPushButton(PatientAppointmentUpdatePage)
        self.btn_ptntUpdateVerify.setGeometry(QtCore.QRect(230, 60, 93, 28))
        self.btn_ptntUpdateVerify.setObjectName("btn_ptntUpdateVerify")
        self.lb_voucherWarn = QtWidgets.QLabel(PatientAppointmentUpdatePage)
        self.lb_voucherWarn.setGeometry(QtCore.QRect(30, 90, 301, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_voucherWarn.setFont(font)
        self.lb_voucherWarn.setObjectName("lb_voucherWarn")
        self.gb_appUpdate = QtWidgets.QGroupBox(PatientAppointmentUpdatePage)
        self.gb_appUpdate.setGeometry(QtCore.QRect(40, 130, 331, 161))
        self.gb_appUpdate.setObjectName("gb_appUpdate")
        self.label_2 = QtWidgets.QLabel(self.gb_appUpdate)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.gb_appUpdate)
        self.label_3.setGeometry(QtCore.QRect(100, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gb_appUpdate)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 40, 191, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.gb_appUpdate)
        self.dateTimeEdit.setGeometry(QtCore.QRect(60, 100, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.btn_ptntUpdateSubmit = QtWidgets.QPushButton(self.gb_appUpdate)
        self.btn_ptntUpdateSubmit.setGeometry(QtCore.QRect(110, 130, 93, 28))
        self.btn_ptntUpdateSubmit.setObjectName("btn_ptntUpdateSubmit")

        self.retranslateUi(PatientAppointmentUpdatePage)
        QtCore.QMetaObject.connectSlotsByName(PatientAppointmentUpdatePage)

    def retranslateUi(self, PatientAppointmentUpdatePage):
        _translate = QtCore.QCoreApplication.translate
        PatientAppointmentUpdatePage.setWindowTitle(_translate("PatientAppointmentUpdatePage", "Electronic Vaccination Data System"))
        self.label.setText(_translate("PatientAppointmentUpdatePage", "Voucher"))
        self.btn_ptntUpdateVerify.setText(_translate("PatientAppointmentUpdatePage", "V e r i f y"))
        self.lb_voucherWarn.setText(_translate("PatientAppointmentUpdatePage", "Incorrect voucher entered, please try again."))
        self.gb_appUpdate.setTitle(_translate("PatientAppointmentUpdatePage", "Appoinment Details"))
        self.label_2.setText(_translate("PatientAppointmentUpdatePage", "Facility"))
        self.label_3.setText(_translate("PatientAppointmentUpdatePage", "Vaccination Date"))
        self.btn_ptntUpdateSubmit.setText(_translate("PatientAppointmentUpdatePage", "B o o k"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PatientAppointmentUpdatePage = QtWidgets.QWidget()
    ui = Ui_PatientAppointmentUpdatePage()
    ui.setupUi(PatientAppointmentUpdatePage)
    PatientAppointmentUpdatePage.show()
    sys.exit(app.exec_())
