# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HealthCareWorkerLoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HealthCareWorkerLoginPage(object):
    def setupUi(self, HealthCareWorkerLoginPage):
        HealthCareWorkerLoginPage.setObjectName("HealthCareWorkerLoginPage")
        HealthCareWorkerLoginPage.resize(429, 300)
        self.lb_username = QtWidgets.QLabel(HealthCareWorkerLoginPage)
        self.lb_username.setGeometry(QtCore.QRect(130, 50, 71, 16))
        self.lb_username.setObjectName("lb_username")
        self.et_hcwUsername = QtWidgets.QLineEdit(HealthCareWorkerLoginPage)
        self.et_hcwUsername.setGeometry(QtCore.QRect(130, 70, 141, 22))
        self.et_hcwUsername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.et_hcwUsername.setObjectName("et_hcwUsername")
        self.label_2 = QtWidgets.QLabel(HealthCareWorkerLoginPage)
        self.label_2.setGeometry(QtCore.QRect(130, 110, 55, 16))
        self.label_2.setObjectName("label_2")
        self.et_hcwPass = QtWidgets.QLineEdit(HealthCareWorkerLoginPage)
        self.et_hcwPass.setGeometry(QtCore.QRect(130, 130, 141, 22))
        self.et_hcwPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.et_hcwPass.setObjectName("et_hcwPass")
        self.btn_hcwSbmitCred = QtWidgets.QPushButton(HealthCareWorkerLoginPage)
        self.btn_hcwSbmitCred.setGeometry(QtCore.QRect(150, 170, 93, 28))
        self.btn_hcwSbmitCred.setObjectName("btn_hcwSbmitCred")
        self.lb_hcwlginun = QtWidgets.QLabel(HealthCareWorkerLoginPage)
        self.lb_hcwlginun.setGeometry(QtCore.QRect(50, 220, 311, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_hcwlginun.setFont(font)
        self.lb_hcwlginun.setObjectName("lb_hcwlginun")
        self.lb_hcwlginpw = QtWidgets.QLabel(HealthCareWorkerLoginPage)
        self.lb_hcwlginpw.setGeometry(QtCore.QRect(50, 240, 311, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_hcwlginpw.setFont(font)
        self.lb_hcwlginpw.setObjectName("lb_hcwlginpw")
        self.lb_hcwlgmissingnfo = QtWidgets.QLabel(HealthCareWorkerLoginPage)
        self.lb_hcwlgmissingnfo.setGeometry(QtCore.QRect(30, 20, 361, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_hcwlgmissingnfo.setFont(font)
        self.lb_hcwlgmissingnfo.setObjectName("lb_hcwlgmissingnfo")
        self.lb_hcwlgnErr = QtWidgets.QLabel(HealthCareWorkerLoginPage)
        self.lb_hcwlgnErr.setGeometry(QtCore.QRect(0, 259, 421, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_hcwlgnErr.setFont(font)
        self.lb_hcwlgnErr.setObjectName("lb_hcwlgnErr")

        self.retranslateUi(HealthCareWorkerLoginPage)
        QtCore.QMetaObject.connectSlotsByName(HealthCareWorkerLoginPage)

    def retranslateUi(self, HealthCareWorkerLoginPage):
        _translate = QtCore.QCoreApplication.translate
        HealthCareWorkerLoginPage.setWindowTitle(_translate("HealthCareWorkerLoginPage", "Electronic Vaccination Data System"))
        self.lb_username.setText(_translate("HealthCareWorkerLoginPage", "Username"))
        self.et_hcwUsername.setPlaceholderText(_translate("HealthCareWorkerLoginPage", "User Name"))
        self.label_2.setText(_translate("HealthCareWorkerLoginPage", "Password"))
        self.et_hcwPass.setPlaceholderText(_translate("HealthCareWorkerLoginPage", "*****"))
        self.btn_hcwSbmitCred.setText(_translate("HealthCareWorkerLoginPage", "S u b m i t"))
        self.lb_hcwlginun.setText(_translate("HealthCareWorkerLoginPage", "Incorrect username Entered, please try again."))
        self.lb_hcwlginpw.setText(_translate("HealthCareWorkerLoginPage", "Incorrect password Entered, please try again."))
        self.lb_hcwlgmissingnfo.setText(_translate("HealthCareWorkerLoginPage", "All the Fields are compulsory, please fill in all of them."))
        self.lb_hcwlgnErr.setText(_translate("HealthCareWorkerLoginPage", "Something went wrong please contact the system administrator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HealthCareWorkerLoginPage = QtWidgets.QWidget()
    ui = Ui_HealthCareWorkerLoginPage()
    ui.setupUi(HealthCareWorkerLoginPage)
    HealthCareWorkerLoginPage.show()
    sys.exit(app.exec_())
