# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HealthCareWorkerReportPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HealthCareWorkerReportPage(object):
    def setupUi(self, HealthCareWorkerReportPage):
        HealthCareWorkerReportPage.setObjectName("HealthCareWorkerReportPage")
        HealthCareWorkerReportPage.resize(400, 300)

        self.retranslateUi(HealthCareWorkerReportPage)
        QtCore.QMetaObject.connectSlotsByName(HealthCareWorkerReportPage)

    def retranslateUi(self, HealthCareWorkerReportPage):
        _translate = QtCore.QCoreApplication.translate
        HealthCareWorkerReportPage.setWindowTitle(_translate("HealthCareWorkerReportPage", "Electronic Vaccination Data System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HealthCareWorkerReportPage = QtWidgets.QWidget()
    ui = Ui_HealthCareWorkerReportPage()
    ui.setupUi(HealthCareWorkerReportPage)
    HealthCareWorkerReportPage.show()
    sys.exit(app.exec_())
