# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HealthCareWorkerVaccinationPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HealthCareWorkerVaccinationPage(object):
    def setupUi(self, HealthCareWorkerVaccinationPage):
        HealthCareWorkerVaccinationPage.setObjectName("HealthCareWorkerVaccinationPage")
        HealthCareWorkerVaccinationPage.resize(392, 300)
        self.groupBox = QtWidgets.QGroupBox(HealthCareWorkerVaccinationPage)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label.setObjectName("label")
        self.et_ptntNamevax = QtWidgets.QLineEdit(self.groupBox)
        self.et_ptntNamevax.setGeometry(QtCore.QRect(10, 40, 113, 22))
        self.et_ptntNamevax.setObjectName("et_ptntNamevax")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 55, 16))
        self.label_2.setObjectName("label_2")
        self.et_ptntvouchvax = QtWidgets.QLineEdit(self.groupBox)
        self.et_ptntvouchvax.setGeometry(QtCore.QRect(10, 90, 113, 22))
        self.et_ptntvouchvax.setObjectName("et_ptntvouchvax")
        self.dt_vaxdatevax = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dt_vaxdatevax.setGeometry(QtCore.QRect(130, 40, 194, 22))
        self.dt_vaxdatevax.setObjectName("dt_vaxdatevax")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(130, 20, 111, 16))
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(140, 70, 55, 16))
        self.label_12.setObjectName("label_12")
        self.et_facilityvax = QtWidgets.QLineEdit(self.groupBox)
        self.et_facilityvax.setGeometry(QtCore.QRect(140, 90, 191, 22))
        self.et_facilityvax.setObjectName("et_facilityvax")
        self.groupBox_2 = QtWidgets.QGroupBox(HealthCareWorkerVaccinationPage)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 341, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_14.setObjectName("label_14")
        self.et_hcwUnVax = QtWidgets.QLineEdit(self.groupBox_2)
        self.et_hcwUnVax.setGeometry(QtCore.QRect(10, 40, 191, 22))
        self.et_hcwUnVax.setText("")
        self.et_hcwUnVax.setObjectName("et_hcwUnVax")
        self.btn_hcwSbmitVax = QtWidgets.QPushButton(HealthCareWorkerVaccinationPage)
        self.btn_hcwSbmitVax.setGeometry(QtCore.QRect(140, 240, 93, 28))
        self.btn_hcwSbmitVax.setObjectName("btn_hcwSbmitVax")

        self.retranslateUi(HealthCareWorkerVaccinationPage)
        QtCore.QMetaObject.connectSlotsByName(HealthCareWorkerVaccinationPage)

    def retranslateUi(self, HealthCareWorkerVaccinationPage):
        _translate = QtCore.QCoreApplication.translate
        HealthCareWorkerVaccinationPage.setWindowTitle(_translate("HealthCareWorkerVaccinationPage", "Electronic Vaccination Data System"))
        self.groupBox.setTitle(_translate("HealthCareWorkerVaccinationPage", "Patient Information"))
        self.label.setText(_translate("HealthCareWorkerVaccinationPage", "Name"))
        self.et_ptntNamevax.setPlaceholderText(_translate("HealthCareWorkerVaccinationPage", "Person"))
        self.label_2.setText(_translate("HealthCareWorkerVaccinationPage", "Voucher"))
        self.et_ptntvouchvax.setPlaceholderText(_translate("HealthCareWorkerVaccinationPage", "Doe"))
        self.label_13.setText(_translate("HealthCareWorkerVaccinationPage", "Vaccination Date"))
        self.label_12.setText(_translate("HealthCareWorkerVaccinationPage", "Facility"))
        self.et_facilityvax.setPlaceholderText(_translate("HealthCareWorkerVaccinationPage", "Steve Biko Hospital"))
        self.groupBox_2.setTitle(_translate("HealthCareWorkerVaccinationPage", "Vaccinator Details"))
        self.label_14.setText(_translate("HealthCareWorkerVaccinationPage", "Username"))
        self.et_hcwUnVax.setPlaceholderText(_translate("HealthCareWorkerVaccinationPage", "Username"))
        self.btn_hcwSbmitVax.setText(_translate("HealthCareWorkerVaccinationPage", "S u b m i t"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HealthCareWorkerVaccinationPage = QtWidgets.QWidget()
    ui = Ui_HealthCareWorkerVaccinationPage()
    ui.setupUi(HealthCareWorkerVaccinationPage)
    HealthCareWorkerVaccinationPage.show()
    sys.exit(app.exec_())
