# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HealthCareWorkerLandingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HealthCareWorkerLandingPage(object):
    def setupUi(self, HealthCareWorkerLandingPage):
        HealthCareWorkerLandingPage.setObjectName("HealthCareWorkerLandingPage")
        HealthCareWorkerLandingPage.resize(400, 300)
        self.btn_hcwLogin = QtWidgets.QPushButton(HealthCareWorkerLandingPage)
        self.btn_hcwLogin.setGeometry(QtCore.QRect(130, 90, 93, 28))
        self.btn_hcwLogin.setObjectName("btn_hcwLogin")
        self.btn_hcwSignup = QtWidgets.QPushButton(HealthCareWorkerLandingPage)
        self.btn_hcwSignup.setGeometry(QtCore.QRect(130, 140, 93, 28))
        self.btn_hcwSignup.setObjectName("btn_hcwSignup")

        self.retranslateUi(HealthCareWorkerLandingPage)
        QtCore.QMetaObject.connectSlotsByName(HealthCareWorkerLandingPage)

    def retranslateUi(self, HealthCareWorkerLandingPage):
        _translate = QtCore.QCoreApplication.translate
        HealthCareWorkerLandingPage.setWindowTitle(_translate("HealthCareWorkerLandingPage", "Electronic Vaccination Data System"))
        self.btn_hcwLogin.setText(_translate("HealthCareWorkerLandingPage", "Login"))
        self.btn_hcwSignup.setText(_translate("HealthCareWorkerLandingPage", "Signup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HealthCareWorkerLandingPage = QtWidgets.QWidget()
    ui = Ui_HealthCareWorkerLandingPage()
    ui.setupUi(HealthCareWorkerLandingPage)
    HealthCareWorkerLandingPage.show()
    sys.exit(app.exec_())
